name: Validate

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: hadolint/hadolint-action@3fc49fb50d59c6ab7917a2e4195dba633e515b29 # v3.2.0
        with:
          dockerfile: "images/*/Dockerfile"
          recursive: true
          config: .hadolint.yaml
      - run: scripts/build-and-test.sh
      - uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          image-ref: ci-ubuntu-base:test
          severity: CRITICAL
          ignore-unfixed: true
          exit-code: "1"
      - uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          image-ref: ci-ubuntu-docker:test
          severity: CRITICAL
          ignore-unfixed: true
          exit-code: "1"
      - name: Report fixed high vulnerabilities
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          image-ref: ci-ubuntu-docker:test
          severity: HIGH
          ignore-unfixed: true
          exit-code: "0"
